// 100% reliable seed data API - no external dependencies
// All data from apps/api/app/services/seed_demo_data.py and seed_peru_regions.py

export const dynamic = 'force-dynamic'

// ============================================================================
// COOPERATIVES DATA (from seed_demo_data.py)
// ============================================================================
const COOPERATIVES = [
  {
    id: 1,
    name: "Cooperativa Agraria Cafetalera Frontera San Ignacio",
    region: "Cajamarca",
    country: "Peru",
    country_code: "PE",
    altitude_m: 1600,
    varieties: "Caturra, Bourbon, Typica",
    certifications: "Organic, Fair Trade, Rainforest Alliance",
    contact_email: "info@cafrontera.com",
    website: "https://www.cafrontera.com",
    status: "active",
    quality_score: 88.5,
    reliability_score: 92.0,
    economics_score: 85.0,
    members_count: 1200,
    annual_production_kg: 800000,
  },
  {
    id: 2,
    name: "CENFROCAFE - Central Fronteriza del Norte de Cafetaleros",
    region: "Cajamarca",
    country: "Peru",
    country_code: "PE",
    altitude_m: 1700,
    varieties: "Caturra, Catimor, Bourbon",
    certifications: "Organic, Fair Trade, UTZ",
    contact_email: "exportaciones@cenfrocafe.com.pe",
    website: "https://www.cenfrocafe.com.pe",
    status: "active",
    quality_score: 86.0,
    reliability_score: 89.0,
    economics_score: 87.5,
    members_count: 2000,
    annual_production_kg: 1200000,
  },
  {
    id: 3,
    name: "Sol y Cafe",
    region: "Cusco",
    country: "Peru",
    country_code: "PE",
    altitude_m: 1800,
    varieties: "Bourbon, Typica, Caturra",
    certifications: "Organic, Fair Trade",
    contact_email: "info@solycafe.com",
    website: "https://www.solycafe.com",
    status: "active",
    quality_score: 90.0,
    reliability_score: 91.0,
    economics_score: 83.0,
    members_count: 650,
    annual_production_kg: 450000,
  },
  {
    id: 4,
    name: "Cooperativa Agraria Norandino",
    region: "Cajamarca",
    country: "Peru",
    country_code: "PE",
    altitude_m: 1500,
    varieties: "Caturra, Bourbon, Pache",
    certifications: "Organic, Fair Trade, Rainforest Alliance, UTZ",
    contact_email: "norandino@norandino.com.pe",
    website: "https://www.norandino.com.pe",
    status: "active",
    quality_score: 87.5,
    reliability_score: 94.0,
    economics_score: 90.0,
    members_count: 7000,
    annual_production_kg: 3500000,
  },
  {
    id: 5,
    name: "CAC Pangoa",
    region: "Junin",
    country: "Peru",
    country_code: "PE",
    altitude_m: 1400,
    varieties: "Caturra, Catimor, Bourbon",
    certifications: "Organic, Fair Trade",
    contact_email: "exportaciones@cacpangoa.com.pe",
    website: "https://www.cacpangoa.com.pe",
    status: "active",
    quality_score: 84.0,
    reliability_score: 87.0,
    economics_score: 86.0,
    members_count: 900,
    annual_production_kg: 600000,
  },
  {
    id: 6,
    name: "Cooperativa Agraria Cafetalera Huadquina",
    region: "Cusco",
    country: "Peru",
    country_code: "PE",
    altitude_m: 1650,
    varieties: "Typica, Bourbon, Caturra",
    certifications: "Organic, Fair Trade, Rainforest Alliance",
    contact_email: "info@huadquina.org",
    website: "https://www.huadquina.org",
    status: "active",
    quality_score: 89.0,
    reliability_score: 88.0,
    economics_score: 84.0,
    members_count: 550,
    annual_production_kg: 380000,
  },
  {
    id: 7,
    name: "Cooperativa de Servicios Multiples Valle de Incahuasi",
    region: "San Martin",
    country: "Peru",
    country_code: "PE",
    altitude_m: 1300,
    varieties: "Caturra, Catimor",
    certifications: "Organic, Fair Trade",
    contact_email: "incahuasi@gmail.com",
    website: null,
    status: "active",
    quality_score: 82.0,
    reliability_score: 85.0,
    economics_score: 80.0,
    members_count: 400,
    annual_production_kg: 250000,
  },
  {
    id: 8,
    name: "CECOCAFEN - Central de Cooperativas Agrarias Cafetaleras",
    region: "Amazonas",
    country: "Peru",
    country_code: "PE",
    altitude_m: 1550,
    varieties: "Caturra, Bourbon, Catimor",
    certifications: "Organic, Fair Trade",
    contact_email: "cecocafen@cecocafen.com.pe",
    website: "https://www.cecocafen.com.pe",
    status: "active",
    quality_score: 85.5,
    reliability_score: 86.0,
    economics_score: 82.5,
    members_count: 1500,
    annual_production_kg: 900000,
  },
  // Colombia
  {
    id: 9,
    name: "Cooperativa de Caficultores de Antioquia",
    region: "Antioquia",
    country: "Colombia",
    country_code: "CO",
    altitude_m: 1750,
    varieties: "Castillo, Caturra, Colombia",
    certifications: "FNC Registered, Organic, Fair Trade",
    contact_email: "info@coopantioquia.com.co",
    website: "https://www.coopantioquia.com.co",
    status: "active",
    quality_score: 87.0,
    reliability_score: 91.0,
    economics_score: 86.0,
    members_count: 3500,
    annual_production_kg: 2100000,
  },
  {
    id: 10,
    name: "Asociacion de Productores de Cafe de Huila",
    region: "Huila",
    country: "Colombia",
    country_code: "CO",
    altitude_m: 1900,
    varieties: "Caturra, Castillo, Geisha",
    certifications: "Organic, Fair Trade, Rainforest Alliance",
    contact_email: "exportaciones@cafehuila.com.co",
    website: "https://www.cafehuila.com.co",
    status: "active",
    quality_score: 91.5,
    reliability_score: 89.0,
    economics_score: 88.0,
    members_count: 1200,
    annual_production_kg: 750000,
  },
  // Ethiopia
  {
    id: 11,
    name: "Yirgacheffe Coffee Farmers Cooperative Union",
    region: "Gedeo Zone, SNNP",
    country: "Ethiopia",
    country_code: "ET",
    altitude_m: 1900,
    varieties: "Heirloom Ethiopian, Typica",
    certifications: "Organic, Fair Trade, ECX Registered",
    contact_email: "info@ycfcu.org",
    website: "https://www.ycfcu.org",
    status: "active",
    quality_score: 93.0,
    reliability_score: 87.0,
    economics_score: 82.0,
    members_count: 45000,
    annual_production_kg: 8000000,
  },
  {
    id: 12,
    name: "Sidama Coffee Farmers Cooperative Union",
    region: "Sidama",
    country: "Ethiopia",
    country_code: "ET",
    altitude_m: 2000,
    varieties: "Heirloom Ethiopian",
    certifications: "Organic, Fair Trade, ECX Registered",
    contact_email: "sidamacoffee@ethionet.et",
    website: "https://www.sidamacoffee.com",
    status: "active",
    quality_score: 91.0,
    reliability_score: 86.0,
    economics_score: 80.0,
    members_count: 72000,
    annual_production_kg: 12000000,
  },
  // Brazil
  {
    id: 13,
    name: "Cooxupe - Cooperativa Regional de Cafeicultores em Guaxupe",
    region: "Minas Gerais",
    country: "Brazil",
    country_code: "BR",
    altitude_m: 900,
    varieties: "Catuai, Mundo Novo, Bourbon",
    certifications: "CECAFE Member, UTZ, Rainforest Alliance",
    contact_email: "exportacao@cooxupe.com.br",
    website: "https://www.cooxupe.com.br",
    status: "active",
    quality_score: 85.0,
    reliability_score: 95.0,
    economics_score: 92.0,
    members_count: 14000,
    annual_production_kg: 75000000,
  },
]

// ============================================================================
// ROASTERS DATA (from seed_demo_data.py)
// ============================================================================
const ROASTERS = [
  {
    id: 1,
    name: "Kaffeeroesterei Speicherstadt",
    city: "Hamburg",
    country: "DE",
    website: "https://www.speicherstadt-kaffee.de",
    contact_email: "kontakt@speicherstadt-kaffee.de",
    peru_focus: true,
    specialty_focus: true,
    price_position: "premium",
    status: "active",
    total_score: 85.0,
    founded_year: 1999,
  },
  {
    id: 2,
    name: "The Barn Berlin",
    city: "Berlin",
    country: "DE",
    website: "https://thebarn.de",
    contact_email: "hello@thebarn.de",
    peru_focus: false,
    specialty_focus: true,
    price_position: "premium",
    status: "active",
    total_score: 92.0,
    founded_year: 2010,
  },
  {
    id: 3,
    name: "Hoppenworth & Ploch",
    city: "Frankfurt",
    country: "DE",
    website: "https://www.hoppenworth-ploch.de",
    contact_email: "info@hoppenworth-ploch.de",
    peru_focus: false,
    specialty_focus: true,
    price_position: "mid",
    status: "active",
    total_score: 78.0,
    founded_year: 2011,
  },
  {
    id: 4,
    name: "Mahlefitz Kaffeeroesterei",
    city: "Muenchen",
    country: "DE",
    website: "https://www.mahlefitz.de",
    contact_email: "info@mahlefitz.de",
    peru_focus: true,
    specialty_focus: true,
    price_position: "premium",
    status: "active",
    total_score: 88.0,
    founded_year: 2015,
  },
  {
    id: 5,
    name: "Five Elephant",
    city: "Berlin",
    country: "DE",
    website: "https://www.fiveelephant.com",
    contact_email: "hello@fiveelephant.com",
    peru_focus: false,
    specialty_focus: true,
    price_position: "premium",
    status: "active",
    total_score: 90.0,
    founded_year: 2010,
  },
  {
    id: 6,
    name: "Bonanza Coffee",
    city: "Berlin",
    country: "DE",
    website: "https://www.bonanzacoffee.de",
    contact_email: "info@bonanzacoffee.de",
    peru_focus: false,
    specialty_focus: true,
    price_position: "premium",
    status: "active",
    total_score: 91.0,
    founded_year: 2006,
  },
  {
    id: 7,
    name: "Elephants & Butterflies Coffee",
    city: "Stuttgart",
    country: "DE",
    website: "https://www.elephants-butterflies.de",
    contact_email: "info@elephants-butterflies.de",
    peru_focus: true,
    specialty_focus: true,
    price_position: "mid",
    status: "active",
    total_score: 82.0,
    founded_year: 2018,
  },
  {
    id: 8,
    name: "Quijote Kaffee",
    city: "Hamburg",
    country: "DE",
    website: "https://www.quijote-kaffee.de",
    contact_email: "info@quijote-kaffee.de",
    peru_focus: true,
    specialty_focus: true,
    price_position: "mid",
    status: "active",
    total_score: 80.0,
    founded_year: 1998,
  },
]

// ============================================================================
// PERU REGIONS DATA (from seed_peru_regions.py)
// ============================================================================
const PERU_REGIONS = [
  {
    id: 1,
    name: "Cajamarca",
    country: "Peru",
    description: "Northern Peru's largest coffee producing region, known for clean, sweet profiles and strong cooperative infrastructure.",
    elevation_min_m: 1200,
    elevation_max_m: 2100,
    avg_temperature_c: 19.5,
    rainfall_mm: 1800,
    humidity_pct: 75,
    soil_type: "Volcanic loam, rich in organic matter",
    production_volume_kg: 75000000,
    production_share_pct: 30.0,
    harvest_months: "April-September",
    typical_varieties: "Bourbon, Caturra, Typica, Catimor",
    typical_processing: "Washed (primary), Honey, Natural",
    quality_profile: "Clean, sweet, balanced acidity, notes of chocolate, caramel, citrus. Consistent quality.",
    main_port: "Callao",
    transport_time_hours: 14.0,
    logistics_cost_per_kg: 0.32,
    infrastructure_score: 84.0,
    weather_risk: "medium",
    political_risk: "low",
    logistics_risk: "low",
    quality_consistency_score: 84.0,
  },
  {
    id: 2,
    name: "Junin",
    country: "Peru",
    description: "Central Peru region (Chanchamayo, Satipo) with excellent logistics and growing specialty focus.",
    elevation_min_m: 1200,
    elevation_max_m: 1800,
    avg_temperature_c: 20.0,
    rainfall_mm: 2000,
    humidity_pct: 78,
    soil_type: "Clay loam with good drainage",
    production_volume_kg: 50000000,
    production_share_pct: 20.0,
    harvest_months: "May-September",
    typical_varieties: "Caturra, Catuai, Typica, Bourbon",
    typical_processing: "Washed, Honey, experimental fermentation",
    quality_profile: "Bright acidity, medium body, fruity notes, floral undertones. Good consistency.",
    main_port: "Callao",
    transport_time_hours: 8.0,
    logistics_cost_per_kg: 0.28,
    infrastructure_score: 88.0,
    weather_risk: "medium",
    political_risk: "low",
    logistics_risk: "low",
    quality_consistency_score: 83.0,
  },
  {
    id: 3,
    name: "San Martin",
    country: "Peru",
    description: "Northern Amazon foothills, growing organic production with higher humidity challenges.",
    elevation_min_m: 900,
    elevation_max_m: 1700,
    avg_temperature_c: 22.0,
    rainfall_mm: 2500,
    humidity_pct: 85,
    soil_type: "Sandy loam, moderate fertility",
    production_volume_kg: 45000000,
    production_share_pct: 18.0,
    harvest_months: "April-August",
    typical_varieties: "Caturra, Catuai, Bourbon, Catimor",
    typical_processing: "Washed, Natural (increasing)",
    quality_profile: "Full body, low to medium acidity, nutty, chocolate notes. Variable quality due to drying challenges.",
    main_port: "Callao",
    transport_time_hours: 18.0,
    logistics_cost_per_kg: 0.38,
    infrastructure_score: 75.0,
    weather_risk: "high",
    political_risk: "low",
    logistics_risk: "medium",
    quality_consistency_score: 81.0,
  },
  {
    id: 4,
    name: "Cusco",
    country: "Peru",
    description: "Southeastern Peru (La Convencion valley), high altitude specialty coffees with complex profiles.",
    elevation_min_m: 1400,
    elevation_max_m: 2200,
    avg_temperature_c: 18.0,
    rainfall_mm: 1600,
    humidity_pct: 70,
    soil_type: "Volcanic, rich organic content",
    production_volume_kg: 37500000,
    production_share_pct: 15.0,
    harvest_months: "April-September",
    typical_varieties: "Typica, Bourbon, Caturra, Catimor",
    typical_processing: "Washed, Honey",
    quality_profile: "Complex, bright acidity, floral, fruity, wine-like notes. Exceptional quality potential.",
    main_port: "Callao",
    transport_time_hours: 24.0,
    logistics_cost_per_kg: 0.42,
    infrastructure_score: 78.0,
    weather_risk: "medium",
    political_risk: "low",
    logistics_risk: "high",
    quality_consistency_score: 86.0,
  },
  {
    id: 5,
    name: "Amazonas",
    country: "Peru",
    description: "Northern Peru, mountainous zones producing small lots with distinct clarity and brightness.",
    elevation_min_m: 1200,
    elevation_max_m: 2100,
    avg_temperature_c: 19.0,
    rainfall_mm: 1900,
    humidity_pct: 80,
    soil_type: "Clay loam, volcanic influence",
    production_volume_kg: 20000000,
    production_share_pct: 8.0,
    harvest_months: "May-September",
    typical_varieties: "Caturra, Bourbon, Typica, Catuai",
    typical_processing: "Washed (dominant)",
    quality_profile: "Clean, bright acidity, citrus, stone fruit, floral notes. High quality micro-lots.",
    main_port: "Callao",
    transport_time_hours: 20.0,
    logistics_cost_per_kg: 0.40,
    infrastructure_score: 76.0,
    weather_risk: "medium",
    political_risk: "low",
    logistics_risk: "medium",
    quality_consistency_score: 85.0,
  },
  {
    id: 6,
    name: "Puno",
    country: "Peru",
    description: "Southern Peru near Lake Titicaca and Bolivia border, very high altitude with distinctive floral profiles.",
    elevation_min_m: 1500,
    elevation_max_m: 2300,
    avg_temperature_c: 17.0,
    rainfall_mm: 1400,
    humidity_pct: 65,
    soil_type: "Volcanic, well-drained",
    production_volume_kg: 12500000,
    production_share_pct: 5.0,
    harvest_months: "May-September",
    typical_varieties: "Bourbon, Typica, Caturra, Catuai",
    typical_processing: "Washed, Natural",
    quality_profile: "Sweet, floral, delicate, complex. Distinctive high-altitude characteristics.",
    main_port: "Callao",
    transport_time_hours: 26.0,
    logistics_cost_per_kg: 0.45,
    infrastructure_score: 72.0,
    weather_risk: "medium",
    political_risk: "low",
    logistics_risk: "high",
    quality_consistency_score: 87.0,
  },
]

// ============================================================================
// MARKET DATA
// ============================================================================
const MARKET_DATA = {
  coffee_prices: {
    arabica_ice: { value: 245.30, change: 3.45, change_pct: 1.43, currency: "USD", unit: "cents/lb" },
    robusta_ice: { value: 4125.00, change: -28.00, change_pct: -0.67, currency: "USD", unit: "USD/ton" },
    peru_fob: { value: 172.50, change: 2.10, change_pct: 1.23, currency: "USD", unit: "cents/lb" },
  },
  exchange_rates: {
    EUR_USD: 1.0825,
    EUR_PEN: 4.02,
    EUR_BRL: 5.45,
    USD_PEN: 3.71,
  },
  certifications_premium: {
    fair_trade: { min: 0.20, max: 0.30, unit: "USD/lb" },
    organic: { min: 0.30, max: 0.50, unit: "USD/lb" },
    rainforest_alliance: { min: 0.10, max: 0.20, unit: "USD/lb" },
  },
  shipping: {
    callao_hamburg: { cost_per_container: 2450, transit_days: 28, currency: "EUR" },
    callao_bremen: { cost_per_container: 2380, transit_days: 30, currency: "EUR" },
    callao_antwerp: { cost_per_container: 2520, transit_days: 26, currency: "EUR" },
  },
}

// ============================================================================
// API HANDLER
// ============================================================================
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const type = searchParams.get('type') || 'all'
  const country = searchParams.get('country')
  const region = searchParams.get('region')
  const id = searchParams.get('id')

  const timestamp = new Date().toISOString()

  try {
    switch (type) {
      case 'cooperatives': {
        let data = COOPERATIVES
        if (country) data = data.filter(c => c.country_code === country.toUpperCase())
        if (region) data = data.filter(c => c.region.toLowerCase().includes(region.toLowerCase()))
        if (id) data = data.filter(c => c.id === parseInt(id))
        return Response.json({ success: true, data, count: data.length, timestamp })
      }

      case 'roasters': {
        let data = ROASTERS
        if (id) data = data.filter(r => r.id === parseInt(id))
        return Response.json({ success: true, data, count: data.length, timestamp })
      }

      case 'regions': {
        let data = PERU_REGIONS
        if (id) data = data.filter(r => r.id === parseInt(id))
        return Response.json({ success: true, data, count: data.length, timestamp })
      }

      case 'market': {
        return Response.json({ success: true, data: MARKET_DATA, timestamp })
      }

      case 'stats': {
        const stats = {
          cooperatives: {
            total: COOPERATIVES.length,
            by_country: {
              PE: COOPERATIVES.filter(c => c.country_code === 'PE').length,
              CO: COOPERATIVES.filter(c => c.country_code === 'CO').length,
              ET: COOPERATIVES.filter(c => c.country_code === 'ET').length,
              BR: COOPERATIVES.filter(c => c.country_code === 'BR').length,
            },
            total_members: COOPERATIVES.reduce((sum, c) => sum + c.members_count, 0),
            total_production_kg: COOPERATIVES.reduce((sum, c) => sum + c.annual_production_kg, 0),
            avg_quality_score: COOPERATIVES.reduce((sum, c) => sum + c.quality_score, 0) / COOPERATIVES.length,
          },
          roasters: {
            total: ROASTERS.length,
            peru_focus: ROASTERS.filter(r => r.peru_focus).length,
            specialty_focus: ROASTERS.filter(r => r.specialty_focus).length,
            avg_score: ROASTERS.reduce((sum, r) => sum + r.total_score, 0) / ROASTERS.length,
          },
          regions: {
            total: PERU_REGIONS.length,
            total_production_kg: PERU_REGIONS.reduce((sum, r) => sum + r.production_volume_kg, 0),
            avg_quality_score: PERU_REGIONS.reduce((sum, r) => sum + r.quality_consistency_score, 0) / PERU_REGIONS.length,
          },
        }
        return Response.json({ success: true, data: stats, timestamp })
      }

      case 'all':
      default: {
        return Response.json({
          success: true,
          data: {
            cooperatives: COOPERATIVES,
            roasters: ROASTERS,
            regions: PERU_REGIONS,
            market: MARKET_DATA,
          },
          counts: {
            cooperatives: COOPERATIVES.length,
            roasters: ROASTERS.length,
            regions: PERU_REGIONS.length,
          },
          timestamp,
        })
      }
    }
  } catch (error) {
    return Response.json(
      { success: false, error: 'Internal server error', timestamp },
      { status: 500 }
    )
  }
}
