name: "Hardening / Tech Debt Task"
description: "Qualität, Security, CI/CD oder Doku-Härtung"
title: "[Hardening] "
labels: ["p1-high", "hardening"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Ziel
      placeholder: Z. B. CORS/Headers härten, Release Gates vereinheitlichen, Doku syncen
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Welche Bereiche/Dateien sind betroffen?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Akzeptanzkriterien
      placeholder: Was muss grün / erfüllt sein?
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priorität
      options:
        - P1
        - P2
        - P3
    validations:
      required: true
  - type: checkboxes
    id: domains
    attributes:
      label: Bereich
      options:
        - label: Backend
        - label: Frontend
        - label: Infra/CI
        - label: Security
        - label: Docs
